spring.application.name=dopapc
app.api.base-url=https://api.escuelajs.co/api/v1

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

minio.endpoint=${MINIO_ENDPOINT}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-products=${MINIO_BUCKET_PRODUCTS}
admin.import-token=${ADMIN_IMPORT_TOKEN}
app.admin.import.enabled=${ADMIN_IMPORT_ENABLED:false}
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=${JWT_ACCESS_TOKEN_EXPIRATION_MS}
jwt.refresh-token-expiration-ms=${JWT_REFRESH_TOKEN_EXPIRATION_MS}
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}